### ISSUE TITLE
Vue.js+Django高性能全栈论道

### ISSUE THREAD

**Issue by stormblinger-ai** [boylegu/theory-D-V-HPFS#114]
大哥你好，正在学习你的Vue.js+Django高性能全栈论道，请问一下有12章节，综合案例源码吗？

**Comment by boylegu** [comment]
我今天晚些时候发给你 多谢支持


发自我的 iPhone

在 2023年5月30日，下午12:15，stormblinger-ai ***@***.***> 写道：

﻿

大哥你好，正在学习你的Vue.js+Django高性能全栈论道，请问一下有12章节，综合案例源码吗？

**Comment by boylegu** [comment]
代码示例已经更新
